#include "../hooligan.h"

char *node_kind_to_str(NodeKind kind)
{
    switch (kind)
    {
    case ND_NUM:
        return "ND_NUM";
    case ND_FLOAT:
        return "ND_FLOAT";
    case ND_ADD:
        return "ND_ADD";
    case ND_SUB:
        return "ND_SUB";
    case ND_MUL:
        return "ND_MUL";
    case ND_DIV:
        return "ND_DIV";
    case ND_MOD:
        return "ND_MOD";
    case ND_EQUAL:
        return "ND_EQUAL";
    case ND_NEQUAL:
        return "ND_NEQUAL";
    case ND_GEQ:
        return "ND_GEQ";
    case ND_LEQ:
        return "ND_LEQ";
    case ND_GTH:
        return "ND_GTH";
    case ND_LTH:
        return "ND_LTH";
    case ND_VAR:
        return "ND_VAR";
    case ND_ASSIGN:
        return "ND_ASSIGN";
    case ND_RETURN:
        return "ND_RETURN";
    case ND_IF:
        return "ND_IF";
    case ND_FOR:
        return "ND_FOR";
    case ND_BLOCK:
        return "ND_BLOCK";
    case ND_WHILE:
        return "ND_WHILE";
    case ND_SWITCH:
        return "ND_SWITCH";
    case ND_CASE:
        return "ND_CASE";
    case ND_FUNC:
        return "ND_FUNC";
    case ND_ARG:
        return "ND_ARG";
    case ND_FUNCDEF:
        return "ND_FUNCDEF";
    case ND_ADDR:
        return "ND_ADDR";
    case ND_DEREF:
        return "ND_DEREF";
    case ND_GVARDEF:
        return "ND_GVARDEF";
    case ND_STRING:
        return "ND_STRING";
    case ND_INIT:
        return "ND_INIT";
    case ND_MEMBER:
        return "ND_MEMBER";
    case ND_BREAK:
        return "ND_BREAK";
    case ND_CONTINUE:
        return "ND_CONTINUE";
    case ND_AND:
        return "ND_AND";
    case ND_OR:
        return "ND_OR";
    case ND_NOT:
        return "ND_NOT";
    case ND_POSTINC:
        return "ND_POSTINC";
    case ND_POSTDEC:
        return "ND_POSTDEC";
    case ND_NOP:
        return "ND_NOP";
    case ND_TYPE:
        return "ND_TYPE";
    default:
        return "NOT_REGISTERD";
    }
}
