name: c CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
  test0:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generation
        run: |
          ./bin/hcli test -g 0
  test1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test main
        run: |
          ./bin/hcli test
  test100:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generation
        run: |
          ./bin/hcli test -g 100
  shellspec:
    needs: setup
    runs-on: ubuntu-latest
    env:
      SHELLSPEC_VERSION: 0.28.1
    steps:
      - uses: actions/checkout@v2
      - name: install shellspec
        run: |
          mkdir -p ~/.local/bin && \
          cd $HOME && \
          wget https://github.com/shellspec/shellspec/archive/${SHELLSPEC_VERSION}.tar.gz && \
          tar xzvf ${SHELLSPEC_VERSION}.tar.gz && \
          cd shellspec-${SHELLSPEC_VERSION} && \
          make install PREFIX="~/.local"
      - name: add path
        run: echo "~/.local/bin" >> $GITHUB_PATH
      - name: run shellspec
        run: |
          ~/.local/bin/shellspec --format documentation
