name: c CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: test compiler
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test main
        env:
          CC: cc
        run: |
          ./bin/hcc testall
