name: c CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: test compiler
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test main
        env:
          CC: cc
        run: |
          ./bin/hcli test all
  selfhost:
    name: selfhost
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: selfhost
        env:
          CC: cc
        run: |
          ./bin/hcli selfhost
  generation:
    name: generation
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: generation
        env:
          CC: cc
        run: |
          ./bin/hcli test -g 100