name: c CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  shellspec:
    runs-on: ubuntu-latest
    env:
      SHELLSPEC_VERSION: 0.28.1
      LD_LIBRARY_PATH: "./bin"
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt update && sudo apt install gdb -y
      - name: install shellspec
        run: |
          cd $HOME && \
          wget https://github.com/shellspec/shellspec/archive/${SHELLSPEC_VERSION}.tar.gz && \
          tar xzvf ${SHELLSPEC_VERSION}.tar.gz
      - name: add path
        run: echo "$HOME/shellspec-${SHELLSPEC_VERSION}/bin" >> $GITHUB_PATH
      - name: run shellspec
        run: |
          shellspec --tag priority:preferably,priority:required
