name: c CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: test main
        run: |
          ./bin/hcli test all
  selfhost:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: selfhost
        run: |
          ./bin/hcli selfhost
  generation:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: generation
        run: |
          ./bin/hcli test -g 100