name: c CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: test compiler
    runs-on: ubuntu-latest
    steps:
      - name: test main
        env:
          CC: cc
        run: make test
            

